# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b047f5d2b92f0c1eca97c397116425dbc8d91a475241e37b9186d1b7e87f16756b9416847bb16fd91e04390510f751a465e0103eefd5cb38e180c9a1432b8e77

test:
  secret_key_base: 8c14b414b5b9025d4cc706d01a3cc659173088d14f2bb3e09a1cf631d8b515d4c30bcf9c45f525c8bd1c21cd2ab3ebfcfb15fde2e964d48fbad37886da76d4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
